title: SISPED IFSULDEMINAS
logo: /image/sisped-logo2.png
description: Sistema de Analise de Dados Pediatricos.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
social-network-links:
  rss: true
  email: "someone@example.com"
staticman:
  repository : "marcos-bah/sisped-ifsuldeminas"
  branch     : master 
