title: SISPED IFSULDEMINAS
logo: /image/sisped-logo1.png
description: Sistema de Analise de Dados Pediatricos.
show_downloads: true
github.zip_url: http://example.com/download.zip 
github :
   zip_url : http://example.com/download.zip 
  another_url : outro valor
